services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    restart:  always
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_HOST
      - POSTGRES_DB
    depends_on:
      - postgres

  postgres:
    image: postgres:17-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
    volumes:
      - ./migrations/:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080