name: Publish Docker Image

on: 
 release:
  types: [created]

jobs:
 build:
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v4
  - name: Build Docker Image
    run: docker build -t learning-docker-image:latest ./05-docker-image-publish
  - name: Login to github container registry
    run: docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.TOKEN_GITHUB}}
  - name: Push Docker Image
    run: docker push learning-docker-image:latest